server:
  port: 80

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_ADDRESS:10.12.107.123:3306}/${MYSQL_DATABASE:ppp}?useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWORD:Zhu12580}
    hikari:
      initialization-fail-timeout: -1
      connection-timeout: 10000
      validation-timeout: 3000

mybatis:
  mapper-locations: classpath*:mapper/*Mapper.xml
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    com.tencent.wxcloudrun: info
